### ISSUE TITLE
Form Components

### ISSUE THREAD

**Issue by danfox01** [Baltimore-County-Government/dotgov-components#11]
Let's try using USPTO's form guidelines as a starting place. The only visual tweak for now is that I want to use our base font size (16pt/22px) and scale all inputs accordingly.

http://uspto.github.io/designpatterns/1.x/docs/components/formControls.html

@martypowell You are our resident form UI expert. Please recommend any changes you think we need.

**Requirements**

Mimic http://uspto.github.io/designpatterns/1.x/docs/components/formControls.html

- Text Input
- Text Area
- Radio Buttons
- Checkboxes
- Select
- Date Picker ???

**Comment by martypowell** [comment]
@danfox01 i am closing this as each of these items (except date picker) has been separated out into their own issues. That will be added when it comes up in the future.
