### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by danfox01** [Baltimore-County-Government/dotgov-components#27]
## Please name the requested component
Table

## Description
- This will be the default styling for all `<table>` elements.
- Table should be striped and allow for row highlighting on hover, behavior similar to [current tables on the .gov](https://www.baltimorecountymd.gov/News/holidays/index.html).

## Required and optional properties
n/a

## Example or Mockup

![FireShot Capture 120 - Dot-Gov-Components - xd adobe com](https://user-images.githubusercontent.com/13049389/63195655-353b5980-c041-11e9-845a-71a9cf8d48c8.png)

See the [design document.](https://xd.adobe.com/spec/e62d55ca-ca05-4c63-7049-04542c2f9ef2-901c/screen/4aa3de60-a9f6-47f1-a746-3ee6e5f19d68/Tables)

## Acceptance Criteria

**Rule Based:**

- Table design, colors, fonts, etc. ,must match design document.
- Table rows must have alternatively striped via CSS, using the colors in the design document.
- Table rows must have a hover state using light gold, as specified in design document.
- Must follow UX standards
- Semantically correct - Must follow [W3C](https://www.w3.org/) standards

## Additional context
In addition to the default table style, we may need a lightweight version (potentially less spacing within cells and a slightly smaller font size) that allows for more content to be shown at once, for data-heavy tables. This decision might need to be TBD based on the how the default table performs.

**Comment by martypowell** [comment]
@danfox01 is there any case where column sorting wouldn't be available?

**Comment by danfox01** [comment]
@martypowell i think it only makes sense in certain cases.  Specifically, small tables probably don't need it, and certain content would never need to be sorted. The example above is a good one -- sorting doesn't provide value and would probably look weird.

**Comment by martypowell** [comment]
@danfox01 ok, so i think its fair to add the basic table initially until we hit one that needs the sorting and potentially filtering?

**Comment by danfox01** [comment]
@martypowell Yep. For this sprint for sure, basic table. The sorting and filtering would prob be more of an advanced component. Updated description above to reflect this.

**Comment by danfox01** [comment]
Larger table example from content area of mockup:
![table](https://user-images.githubusercontent.com/13049389/62872396-60dddd00-bceb-11e9-9726-91a3f9c349e4.jpg)

**Comment by danfox01** [comment]
Added acceptance criteria.
