### ISSUE TITLE
Text Input

### ISSUE THREAD

**Issue by martypowell** [Baltimore-County-Government/dotgov-components#28]
**Please name the requested component**
TextInput

**Please describe the requested component**
Component should use default functionality based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input as a guideline

**Please describe any required and optional properties for the component**

- Hint - type - string - only when absolutely necessary, adds text to help the user fill out a field, ex Password Requirements
- Label - type - string - Label to describe the associated text input
- Id - type - string - Unique identifier used to associate the input with the label

**Example or Mockup**

_Default State_

![image](https://user-images.githubusercontent.com/1933400/62624954-42926e80-b8f2-11e9-8611-3064ef6046ab.png)

_Focused_

![image](https://user-images.githubusercontent.com/1933400/62625056-7372a380-b8f2-11e9-8b4c-fea0b3636160.png)

**Acceptance Criteria**

**Rule Based**:

- Each text input requires a label
- Label when selected must focus on the input
- When hint is present, visible underneath the label
- Must follow UX standards
- Semantically correct - Must follow [W3C](https://www.w3.org/) standards
- Matches Mockup Styles

**Additional context**

We will want to allow for this field to be validated, but that can be handled independently of this change.

**Comment by sdurphy** [comment]
Just FYI all, the focus color should be #1076BC (Blue Vibrant), not gold.
