### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by martypowell** [Baltimore-County-Government/dotgov-components#32]
**Please name the requested component**
TextArea

**Please describe the requested component**
Component should use default functionality based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textareaas a guideline

**Please describe any required and optional properties for the component**

- **Hint** - type - _string_ - only when absolutely necessary, adds text to help the user fill out a field, ex Password Requirements
- **Label** - type - _string_ - Label to describe the associated text input
- **Id** - type - string - Unique identifier used to associate the input with the label

**Example or Mockup**

Should look most likely the [text input](https://github.com/baltimorecounty/dotgov-components/issues/28)

**Acceptance Criteria**

**Rule Based**:

- Each text input requires a label
- Label when selected must focus on the input
- When hint is present, visible underneath the label
- Must follow UX standards
- Semantically correct - Must follow [W3C](https://www.w3.org/) standards
- Matches Mockup Styles

**Additional context**

The textarea to be equivalent to 5 lines of input text for minimum height.

**Comment by martypowell** [comment]
@danfox01 once piece of information we probably should include is a `min-height`?

**Comment by danfox01** [comment]
@martypowell, good point. I think we want the `textarea` to be equivalent to 5 lines of input text. So whether that is accomplished with something like `5em` or a fixed height if up to you, but the result should be the user being able to see 5 full lines of textbefore scrolling.
