### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by martypowell** [Baltimore-County-Government/dotgov-components#37]
**Please name the requested component**
Button

**Please describe the requested component**
Use the default behavior based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Please describe any required and optional properties for the component**
Only styles are applied right now.

**Example or Mockup**

https://xd.adobe.com/spec/6c7ed8ba-6428-418d-464e-d31fb3608c6b-1a4f/

**Acceptance Criteria**

**Rule Based**:

- Must handle the followings states
  - default
  - focused
  - hovered
  - disabled
- Must follow UX standards
- Semantically correct - Must follow [W3C](https://www.w3.org/) standards
- Matches Mockup Styles

**Additional context**

This might be a little fluid, and developers should work with designers on this component closely.

**Comment by martypowell** [comment]
@danfox01 in baltcogo we have the option to include an icon in the button, is that something we want to include in this system?

**Comment by martypowell** [comment]
> @danfox01 in baltcogo we have the option to include an icon in the button, is that something we want to include in this system?

this is different than icons buttons, in this case an example would be.

default state: Submit Form
sumbitting state: loading icon plus submitting form

something along those lines.

**Comment by martypowell** [comment]
@danfox01 not sure where this gets documented, but wanted to call out that a button must be included in a snippet, form, or an external app. Limitation of site executive.

Whether this is important or not, I don't know.

**Comment by martypowell** [comment]
@sdurphy well need to be sure to handle all of the states.  https://cloudfour.com/thinks/designing-button-states/

I believe we want to cover the following?

- default
- focused
- hovered
- disabled

fyi @danfox01

**Comment by danfox01** [comment]
Wow @martypowell... getting caught up. We can mock up all button types and all states, and include above. @sdurphy, I'll hit you up this thread to keep it from blowing up.

**Comment by martypowell** [comment]
@danfox01 @sdurphy referencing the inspiration for this

https://designsystem.digital.gov/components/button/
