### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by martypowell** [Baltimore-County-Government/dotgov-components#38]
## Component Name
N/A, but should include:
- `h1`
- `h2`
- `h3`
- `h4`-`h6` (these headings have  identical styling)
- `p`

## Please describe the requested component
Default functionality with styling see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

**Please describe any required and optional properties for the component**

n/a

## Example or Mockup

Please see [design document.](https://xd.adobe.com/spec/e62d55ca-ca05-4c63-7049-04542c2f9ef2-901c/screen/140a31f7-1ebe-4590-8c2a-979b8fef6abc/Typography/)

## Acceptance Criteria

**Rule Based**:

- Must match visual styles defined in the design document.
- Must follow UX standards
- Semantically correct - Must follow [W3C](https://www.w3.org/) standards

## Additional context

- These will not require any react components, but will require a documentation file. Not sure how this will work. (-MP)
- These are based on the heading and text styles that will be most common on the site. A number of alternative and context-specific versions of headings and p tags will be required in future springs.

**Comment by danfox01** [comment]
@martypowell what sort of documentation do you need for this? Style info from Sam?

**Comment by martypowell** [comment]
Yea i think so, this one is kinda setup, but it should be logged.

**Comment by danfox01** [comment]
@sdurphy can you please provide the details for this? Font faces, weights, sizes for body, headings etc.

**Comment by danfox01** [comment]
@martypowell @sdurphy 

Need the following base fonts , I think:

- Heading 1
- Heading 2
- Heading 3
- Heading 4 (5 and 6 styled the same as 4)
- Paragraph
- Ordered list
- Unordered list
- Block Quote
