### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by martypowell** [Baltimore-County-Government/dotgov-components#53]
## Component Name

n/a this information only and the result of the work will be color variables. See [colors guide](https://github.com/baltimorecounty/dotgov-components/wiki/Colors).

## Description

See [colors guide](https://github.com/baltimorecounty/dotgov-components/wiki/Colors).

## Required and optional properties

n/a 

## Example or Mockup

Values are defined in the design document, here: https://xd.adobe.com/spec/e62d55ca-ca05-4c63-7049-04542c2f9ef2-901c/screen/63f55c61-66fc-47a2-b01d-df0c8bb7cf55/Colors

**NOTE**: 8/20/2019 - Matches mockup with [this](https://github.com/baltimorecounty/dotgov-components/issues/53#issuecomment-523073656) minor change

## Acceptance Criteria

- Variables defined according to [design system.](https://github.com/baltimorecounty/dotgov-components/wiki/Colors)
- Values match those defined in [XD design documentation.](https://xd.adobe.com/spec/e62d55ca-ca05-4c63-7049-04542c2f9ef2-901c/screen/63f55c61-66fc-47a2-b01d-df0c8bb7cf55/Colors)

## Additional context

n/a

**Comment by martypowell** [comment]
@sdurphy @danfox01 if you guys can provide these values, we can make sure they mathematically work.

**Comment by danfox01** [comment]
Added link to values and added acceptance criteria.

**Comment by martypowell** [comment]
@danfox01 @sdurphy per a gchat, we are going to modify this slightly from the mockup.

The grayscale will match the pattern for the other colors, but will add a white and black as well.

```scss
$gray-lightest-ratio: 95%;
$gray-light-ratio: 60%;

$gray: #666;
$gray-lightest: mix(white, $gray, $gray-lightest-ratio);
$gray-light: mix(white, $gray, $gray-light-ratio);
$gray-dark: mix(black, $gray, $gray-light-ratio);
$gray-darkest: mix(black, $gray, $gray-lightest-ratio);
$black: black;
$white: white;
```

In the current mockup $gray-darkest was set to 100% which results in black. So it's  a very minor adjustment.

**Comment by danfox01** [comment]
@sdurphy Do we plan to use true black for text, or are we using something like 95%?

**Comment by sdurphy** [comment]
Base headings, lead copy, and quotes are black, all other text should be $gray-dark
