### ISSUE TITLE
Homepage Assembly

### ISSUE THREAD

**Issue by danfox01** [Baltimore-County-Government/dotgov-components#91]
The final final expected deliverable for this sprint is a complete static build of the home page, uploaded to a location where Web Services can review it.

## Acceptance Criteria

- Available in a location where the web team can access it, such as github.io or Now.
- Assembled from components that were built previously in this sprint.
- Layout and breakpoints generally match the homepage prototype: http://staging.baltimorecountymd.gov/county-prototype/index.html.
- Search and News Feed are expected to be placeholder only.

**Comment by martypowell** [comment]
@danfox01 my expectation is that it will be a react app (create react app) that imports our styleguide components. keeping dev version in now and the prod version probably for github.io probably makes sense in this case too.

**Comment by martypowell** [comment]
*any components added as part of the process, would remain in the styleguide

**Comment by martypowell** [comment]
Ended up being done as part of prototype type tasks, closing.
